# Generated by Django 5.1.4 on 2025-03-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemetadata',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='userkey',
            name='user',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='FileMetadata',
        ),
        migrations.DeleteModel(
            name='UserKey',
        ),
    ]
