# Generated by Django 5.1.2 on 2025-04-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_auditlog_options_remove_auditlog_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
