# Generated by Django 4.2.29 on 2026-04-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auditlog_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemetadata',
            name='file_type',
            field=models.CharField(max_length=255),
        ),
    ]
