# Generated by Django 4.2.29 on 2026-04-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_filemetadata_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=150)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_hash', models.CharField(blank=True, default='', max_length=64)),
                ('details', models.TextField(blank=True, default='')),
                ('previous_hash', models.CharField(max_length=64)),
                ('block_hash', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
