# Generated by Django 5.1.2 on 2025-05-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
